# Ini Komentar
FROM alpine

LABEL author="Andry Pebrianto"
LABEL company="Nibiru Developer" website="https://nilabiru.com"

RUN mkdir hello
# ADD text/*.txt hello
ADD text/* hello

CMD cat "hello/world.txt"
