version: "3.8"

services:
  nginx-port1:
    container_name: nginx-port1
    image: nginx
    ports:
      - protocol: tcp
        published: 8001
        target: 80
    deploy:
      resources:
        reservations:
          cpus: "0.25"
          memory: 50M
        limits:
          cpus: "0.5"
          memory: 100M
