version: "3.8"

services:
  nginx-port1:
    container_name: nginx-port1
    image: nginx
    ports:
      - protocol: tcp
        published: 8001
        target: 80
  nginx-port2:
    container_name: nginx-port2
    image: nginx
    ports:
      - 8082:80
