# Ini Komentar
FROM alpine

LABEL author="Andry Pebrianto"
LABEL company="Nibiru Developer" website="https://nilabiru.com"

RUN mkdir hello
RUN echo "Hello World" > "hello/word.txt"

CMD cat "hello/word.txt"
