version: "3.8"

services:
  db1:
    image: mongo
    container_name: db-mongo
    ports:
      - "27777:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aswassaw
      - MONGO_INITDB_ROOT_PASSWORD=aswassaw
      - MONGO_INITDB_DATABASE=admin
